# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='total',
            field=models.IntegerField(default='0'),
        ),
    ]
